name: Deploy Conta Service

on:
  push:
    branches:
      - main
    paths:
      - "conta-service/**"

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "[1] Checkout do código"
        uses: actions/checkout@v4

      # CORREÇÃO: Instalar Docker Compose diretamente
      - name: "[2] Instalar Docker Compose"
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: "[3] Configurar JDK 21"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: "[4] Configurar Maven"
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: "[5] Cache Maven"
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('conta-service/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: "[6] Build e Package"
        run: |
          echo "🏗️  Building Conta Service..."
          cd conta-service
          mvn clean compile package -DskipTests

      - name: "[7] Build Docker Image"
        run: |
          echo "🐳 Building Docker image..."
          docker build -t conta-service:latest ./conta-service

      # CORREÇÃO: Usar docker-compose v1
      - name: "[8] Testar com Docker Compose"
        run: |
          echo "🐳 Testando com Docker Compose..."
          cd infra
          docker-compose up -d conta-service postgres kafka-broker zookeeper
          sleep 30
          docker-compose logs conta-service --tail=20
          docker-compose ps
          docker-compose down

      - name: "[9] Deploy via SSH"
        run: echo "✅ Build e testes concluídos - Pronto para deploy"