name: Deploy Conta Service

on:
  push:
    branches:
      - main
    paths:
      - "conta-service/**"

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: "[1] Checkout do código"
        uses: actions/checkout@v4

      # 2️⃣ Configurar JDK 21
      - name: "[2] Configurar JDK 21"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 2.1️⃣ Instalar Maven 3.10+
      - name: "[2.1] Instalar Maven 3.10+"
        run: |
          MAVEN_VERSION=3.10.1
          wget https://dlcdn.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
          tar xzf apache-maven-$MAVEN_VERSION-bin.tar.gz
          sudo mv apache-maven-$MAVEN_VERSION /opt/maven
          export PATH=/opt/maven/bin:$PATH
          mvn -version

      # 3️⃣ Cache Maven
      - name: "[3] Cache Maven"
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('conta-service/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Build JAR
      - name: "[4] Build JAR"
        run: mvn -f conta-service/pom.xml clean package -DskipTests

      # 5️⃣ Build Docker Image
      - name: "[5] Build Docker Image"
        run: docker build -t conta-service:latest ./conta-service

      # 6️⃣ Deploy via SSH (placeholder)
      - name: "[6] Deploy via SSH"
        run: echo "Enviar app.jar ou subir container na VPS"
