name: Deploy Conta Service

on:
  push:
    branches:
      - main
    paths:
      - "conta-service/**"

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "[1] Checkout do código"
        uses: actions/checkout@v4

      - name: "[2] Configurar JDK 21"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: "[3] Configurar Maven"
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: "[4] Cache Maven"
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('conta-service/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: "[5] Build e Package"
        run: |
          echo "🏗️  Building Conta Service..."
          cd conta-service
          mvn clean compile package -DskipTests

      - name: "[6] Build Docker Image"
        run: |
          echo "🐳 Building Docker image..."
          docker build -t conta-service:latest ./conta-service

      - name: "[7] Testar com Docker Compose"
        run: |
          echo "🐳 Testando com Docker Compose da pasta infra..."
          cd infra
          docker-compose up -d conta-service
          sleep 15
          docker-compose logs conta-service
          docker-compose down

      - name: "[8] Deploy via SSH"
        run: echo "✅ Build concluído - Pronto para deploy"