name: "Deploy Spring Boot API"
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "[1] Baixar o código"
        uses: actions/checkout@v4

      - name: "[2] Configurar o JDK 21"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: "[3] Compilar e gerar o JAR"
        run: mvn clean package -DskipTests