name: Deploy Microserviços Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [conta-service, kafka-service]

    steps:
      # 1️⃣ Checkout do código
      - name: "[1] Checkout do código"
        uses: actions/checkout@v4

      # 2️⃣ Configurar JDK 21
      - name: "[2] Configurar JDK 21"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3️⃣ Configurar cache do Maven
      - name: "[3] Cache Maven"
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Build JAR
      - name: "[4] Build JAR"
        run: mvn -f ${{ matrix.service }}/pom.xml clean package -DskipTests

      # 5️⃣ Build Docker Image
      - name: "[5] Build Docker Image"
        run: docker build -t ${{ matrix.service }}:latest ./${{ matrix.service }}

      # 6️⃣ Push Docker Image para registry (opcional)
      # - name: "[6] Push Docker Image"
      #   run: docker push seu-registry/${{ matrix.service }}:latest

      # 7️⃣ Deploy via SSH (placeholder)
      - name: "[7] Deploy via SSH"
        run: |
          echo "Adicionar comandos de SCP/SSH para enviar o JAR ou subir container na VPS"
