name: Deploy Microserviços Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [conta-service, kafka-service]

    steps:
      - name: "[1] Checkout do código"
        uses: actions/checkout@v4

      - name: "[2] Configurar JDK 21"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: "[3] Cache Maven"
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: "[4] Build JAR (local test)"
        run: mvn -f ${{ matrix.service }}/pom.xml clean package -DskipTests

      - name: "[5] Build Docker Image"
        run: docker build \
          -f infra/Dockerfile \
          --build-arg MODULE=${{ matrix.service }} \
          -t ${{ matrix.service }}:latest .

      # - name: "[6] Push Docker Image"
      #   run: docker push seu-registry/${{ matrix.service }}:latest

      - name: "[7] Deploy via SSH"
        run: |
          echo "Adicionar comandos de SCP/SSH para enviar o JAR ou subir container na VPS"
