name: Deploy Log Service

on:
  push:
    branches: [ main ]
    paths: [ 'log-service/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'log-service/**' ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: funcoesdb

    steps:
      - name: "[1] Checkout do código"
        uses: actions/checkout@v4

      - name: "[2] Configurar JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: "[3] Build Projeto Raiz"
        run: mvn clean install -DskipTests

      - name: "[4] Build e Testes Log Service"
        run: |
          cd log-service
          mvn clean compile test package

      - name: "[5] Docker Build"
        run: |
          cd log-service
          docker build -t log-service:latest .

      - name: "[6] Integration Test"
        run: |
          cd infra
          docker compose --env-file <(printenv) up -d log-service postgres-db kafka-broker zookeeper
          sleep 45
          curl -f http://localhost:8083/actuator/health || exit 1
          docker compose down

      - name: "[7] Deploy (Placeholder)"
        if: github.ref == 'refs/heads/main'
        run: echo "🚀 Deploy para produção aqui..."
